name: Test 2
favicon: null
layout_spectrum: 0.8
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#27262b'
    - '#4c574f'
    - '#d1dfe9'
    - '#bac0b4'
    - '#b99ead'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
